services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: fastapi_app_dev
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - .:/app
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:17
    container_name: fastapi_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot_dht_pg
    volumes:
      - db_data_dev:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: fastapi_nginx_dev
    ports:
      - "8083:80"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

volumes:
  db_data_dev:
