services:
  app:
    image: ${APP_IMAGE}
    container_name: fastapi_app_prod
    env_file:
      - .env.prod
    command: sh -c "alembic upgrade head && uvicorn main:app --host=0.0.0.0 --port=8000 --workers=2"

  nginx:
    image: ${NGINX_IMAGE}
    container_name: nginx_service
    ports:
      - "80:80"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
